name: Label issues and PRs

on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Label by title prefix
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const title = context.payload.pull_request?.title || context.payload.issue?.title;
            const number = context.payload.pull_request?.number || context.payload.issue?.number;
            const isPR = !!context.payload.pull_request;

            const labelsMap = {
              feat: "feat",
              bug: "bug",
              chore: "chore",
              test: "test",
              documentation: "documentation",
              refactor: "refactor",
              style: "style"
            };

            const prefix = title.split(":")[0].toLowerCase();

            if (labelsMap[prefix]) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: number,
                labels: [labelsMap[prefix]],
              });
            }
